import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Form from "../components/Form";
export default function Home() {
    const [forms, setForms] = useState(1);
    return (
        <div className={styles.container}>
            <Head>
                <title>NFT API Benchmark</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h4>NFT API Benchmark</h4>
                <div className={styles.Forms}>
                    {[...Array(forms)].map((_, i) => (
                        <Form key={i}></Form>
                    ))}
                    <div className={styles.buttons}>
                        <button
                            onClick={() => setForms(forms + 1)}
                            className={styles.add}
                        >
                            +
                        </button>
                        {forms != 1 && (
                            <button
                                onClick={() =>
                                    forms != 1 && setForms(forms - 1)
                                }
                                className={styles.add}
                            >
                                -
                            </button>
                        )}
                    </div>
                </div>
            </main>
        </div>
    );
}
